# Template only; fill via env vars in local/CI
veracitypro_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'DBT_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'VP_DWH') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'WH_INGEST') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'STG') }}"
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'DBT_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'VP_DWH') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'WH_INGEST') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'STG') }}"
