# models/marts/schema.yml
# Summary:
# - Relationship and uniqueness tests for star schema.
version: 2
models:
  - name: dim_product
    columns:
      - name: asin
        tests: [unique, not_null]

  - name: dim_category
    columns:
      - name: category_id
        tests: [unique, not_null]

  - name: dim_product_category
    columns:
      - name: pk
        tests: [unique, not_null]
      - name: asin
        tests:
          - relationships: {arguments: {to: ref('dim_product'), field: asin}}
      - name: category_id
        tests:
          - relationships: {arguments: {to: ref('dim_category'), field: category_id}}

  - name: fct_price_history_daily
    columns:
      - name: pk
        tests: [unique, not_null]
      - name: asin
        tests:
          - relationships: {arguments: {to: ref('dim_product'), field: asin}}

  - name: fct_rank_history_daily
    columns:
      - name: pk
        tests: [unique, not_null]
      - name: asin
        tests:
          - relationships: {arguments: {to: ref('dim_product'), field: asin}}

  - name: fct_review_history_daily
    columns:
      - name: pk
        tests: [unique, not_null]
      - name: asin
        tests:
          - relationships: {arguments: {to: ref('dim_product'), field: asin}}

  - name: fct_offer_price_daily
    columns:
      - name: pk
        tests: [unique, not_null]
      - name: asin
        tests:
          - relationships: {arguments: {to: ref('dim_product'), field: asin}}