# models/stg/schema.yml
# Summary:
# - Column-level tests for staging; allow NULL for Keepa sentinels mapped to NULL.
version: 2
models:
  - name: stg_keepa_price
    columns:
      - name: asin
        tests: [not_null]
      - name: price
        tests:
          - dbt_utils.expression_is_true:
              expression: "price is null or price >= 0"
  - name: stg_keepa_rank
    columns:
      - name: asin
        tests: [not_null]
      - name: rank
        tests:
          - dbt_utils.expression_is_true:
              expression: "rank is null or rank > 0"
  - name: stg_keepa_reviews
    columns:
      - name: asin
        tests: [not_null]
      - name: rating
        tests:
          - dbt_utils.expression_is_true:
              expression: "rating is null or (rating >= 0 and rating <= 5)"
      - name: review_count
        tests:
          - dbt_utils.expression_is_true:
              expression: "review_count is null or review_count >= 0"
  - name: stg_keepa_offers
    columns:
      - name: asin
        tests: [not_null]
      - name: offer_id
        tests: [not_null, unique]
  - name: stg_keepa_offer_price
    columns:
      - name: asin
        tests: [not_null]
      - name: offer_id
        tests: [not_null]
  - name: stg_keepa_aplus_module
    columns:
      - name: asin
        tests: [not_null]
      - name: asset_type
        tests:
          - accepted_values:
              values: ['image','image_alt','text','video']
  - name: stg_keepa_videos
    columns:
      - name: asin
        tests: [not_null]
      - name: stg_video_id
        tests: [unique, not_null]
