name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dbt-compile:
    name: dbt deps + compile
    runs-on: ubuntu-latest
    defaults:
      run:
        # where dbt_project.yml lives in your repo
        working-directory: dbt/veracitypro_dbt
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dbt (Snowflake)
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-core>=1.10,<1.11" "dbt-snowflake>=1.10,<1.11"

      - name: Install dbt packages
        run: dbt deps

      - name: Create temporary profiles.yml (compile only)
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/.ci"
          cat > "${GITHUB_WORKSPACE}/.ci/profiles.yml" <<'EOF'
          veracitypro_dbt:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: dummy
                user: dummy
                password: dummy
                role: DUMMY
                database: DUMMY
                warehouse: DUMMY
                schema: CI
                threads: 1
          EOF

      - name: Parse & compile
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/.ci
        run: |
          dbt parse --warn-error
          dbt compile

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Ruff check
        run: ruff check --format=github .

  tests:
    runs-on: ubuntu-latest
    # wrap the expression in ${{ ... }} so it's valid
    if: ${{ hashFiles('tests/**') != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest fastjsonschema
      - name: Run unit tests
        run: pytest -q
