name: CI

on:
  push:
    branches: ['**']        # run on any branch push (useful while stabilizing)
  pull_request:
    branches: [main, develop]

jobs:
  dbt-compile:
    name: dbt deps + compile
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbt/veracitypro_dbt       # where dbt_project.yml lives
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dbt (Snowflake)
        run: |
          python -m pip install --upgrade pip
          # keep dbt-snowflake pinned to <1.11 so adapters match
          pip install "dbt-core>=1.10,<1.11" "dbt-snowflake>=1.10,<1.11"

      - name: Install dbt packages (dbt deps)
        run: dbt deps

      - name: Create temp profiles.yml (compile only)
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/.ci"
          cat > "${GITHUB_WORKSPACE}/.ci/profiles.yml" << 'EOF'
          veracitypro_dbt:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: dummy
                user: dummy
                password: dummy
                role: DUMMY
                database: DUMMY
                warehouse: DUMMY
                schema: CI
                threads: 1
          EOF

      - name: dbt compile
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/.ci
        run: dbt compile

  lint:
    name: Ruff (strict)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Ruff check
        run: ruff check --format=github .

  tests:
    name: Unit tests
    if: ${{ hashFiles('tests/**') != '' }}   # skip if you have no tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest fastjsonschema requests
      - name: Run tests
        run: pytest -q
