name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  dbt-compile:
    name: dbt deps + compile
    runs-on: ubuntu-latest
    # All dbt commands run from your dbt project folder
    defaults:
      run:
        working-directory: dbt/veracitypro_dbt
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-core>=1.10,<1.11" "dbt-snowflake>=1.10,<1.11"

      - name: Install dbt packages
        run: dbt deps

      - name: Create temp profiles.yml (no real creds)
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/.ci"
          cat > "${GITHUB_WORKSPACE}/.ci/profiles.yml" <<'EOF'
          veracitypro_dbt:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: dummy
                user: dummy
                password: dummy
                role: DUMMY
                database: VP_DWH
                warehouse: WH_INGEST_XS
                schema: RAW
                threads: 1
          EOF

      - name: Parse & compile dbt project
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/.ci
        run: |
          dbt parse
          dbt compile

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      # STRICT (fails PR on style issues):
      - name: Ruff check
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          ruff check --format=github .
      # If you want to be lenient for now, replace the step above with:
      # - name: Ruff (non-blocking)
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install ruff
      #     ruff check --exit-zero --format=github .

  tests:
    # Only run if there are tests
    if: ${{ hashFiles('tests/**') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run unit tests
        run: pytest -q
