name: CI

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  dbt-compile:
    name: dbt deps + compile
    runs-on: ubuntu-latest
    # All dbt commands run from your dbt project folder
    defaults:
      run:
        working-directory: dbt/veracitypro_dbt

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dbt (Snowflake adapter)
        run: |
          python -m pip install --upgrade pip
          # Pin to current major to avoid surprise upgrades
          pip install "dbt-core>=1.10,<1.11" "dbt-snowflake>=1.10,<1.11"

      - name: Install dbt packages (dbt deps)
        run: dbt deps

      - name: Create temp profiles.yml (compile-only; no real creds)
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/.ci"
          cat > "${GITHUB_WORKSPACE}/.ci/profiles.yml" <<'EOF'
          veracitypro_dbt:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: dummy
                user: dummy
                password: x
                role: DUMMY
                database: DUMMY
                warehouse: DUMMY
                schema: CI
                threads: 1
          EOF

      - name: dbt compile
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/.ci
        run: dbt compile

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Non-blocking for now; change to `ruff check .` when you're ready
      - name: Ruff check (report only)
        run: ruff check --exit-zero --format=github .

  tests:
    # Only run if you actually have tests
    if: ${{ hashFiles('tests/**') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run unit tests
        run: pytest -q
