name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dbt-compile:
    name: dbt deps + compile
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbt/veracitypro_dbt
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt (Snowflake)
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-core>=1.10,<1.11" "dbt-snowflake>=1.10,<1.11"

      - name: Install dbt packages
        run: dbt deps

      - name: Create temporary profiles.yml (compile only)
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/.ci"
          cat > "${GITHUB_WORKSPACE}/.ci/profiles.yml" <<'EOF'
          veracitypro_dbt:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: dummy
                user: dummy
                password: dummy
                role: DUMMY
                database: DUMMY
                warehouse: DUMMY
                schema: CI
                threads: 1
          EOF

      - name: Parse & compile
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/.ci
        run: |
          dbt parse --warn-error
          dbt compile

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Ruff check
        run: ruff check --format=github .

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest fastjsonschema

      - id: detect
        name: Detect test files
        shell: bash
        run: |
          shopt -s globstar nullglob
          files=(tests/**/*.py tests/*.py)
          if [ ${#files[@]} -gt 0 ]; then
            echo "has_tests=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_tests=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run unit tests
        if: steps.detect.outputs.has_tests == 'true'
        run: pytest -q

      - name: No tests found (skip)
        if: steps.detect.outputs.has_tests != 'true'
        run: echo "No Python tests under ./tests — skipping."
